name: Frontend CI

on:
   push:
      branches: [main, hw-9-ci-cd]
   pull_request:
      branches: [main, hw-9-ci-cd]

jobs:
   build-and-test:
      runs-on: ubuntu-latest

      steps:
         - name: Checkout code
           uses: actions/checkout@v4

         - name: Cache node_modules
           uses: actions/cache@v4
           with:
              path: |
                 **/node_modules
              key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
              restore-keys: |
                 ${{ runner.os }}-node-

         - name: Set up Node.js
           uses: actions/setup-node@v4
           with:
              node-version: 20

         - name: Install dependencies
           run: npm ci

         - name: Run ESLint
           run: npx eslint . --ext .ts,.tsx

         - name: Type check
           run: npx tsc --noEmit

         - name: Build frontend
           run: npm run build

         - name: Run unit tests
           run: npx vitest run src/tests/unit --coverage

         - name: Upload build artifact
           uses: actions/upload-artifact@v4
           with:
              name: frontend-build
              path: dist

         - name: Upload test coverage
           uses: actions/upload-artifact@v4
           with:
              name: test-coverage
              path: coverage
